- src/components/Buttons/StatusChangeButton.jsx
- src/components/Cards/StatusCard.jsx
- src/components/Searchbar/CommonSearchBar.jsx
- src/components/layouts/Sidenav.jsx
- src/pages/customer/Delivery.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderSubscription.jsx
- src/pages/customer/ProductTimesale.jsx
- src/pages/customer/Promotion.jsx
- 구현 기능을 적어주세요.
- #2 
- #3 
- git flow 전략으로 수정하기 위한 pr
> Feat/2 주문페이지 공통 컴포넌트 구현

- src/pages/customer/Delivery.jsx
> KAN-164 feat: 배송관리페이지 테이블생성

- package-lock.json
- package.json
- src/components/Searchbar/CommonSearchBar.jsx
- src/pages/customer/MemberManage.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-8](https://badgen.net/badge/Preview/PR-8/blue)](https://pr-8.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원관리 - 회원조회 페이지 UI 구현
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
pull request 배지 잘 적용되는지 확인용 pr
> KAN-175 feat/회원관리-회원조회UI

- package-lock.json
- package.json
- src/components/Buttons/StatusChangeButton.jsx
- src/pages/customer/Delivery.jsx
- src/pages/customer/MemberManage.jsx
[![KAN-195](https://badgen.net/badge/JIRA/KAN-195/blue?icon=jira)](https://jira.company.com/browse/KAN-195) [![PR-13](https://badgen.net/badge/Preview/PR-13/blue)](https://pr-13.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 배송관리페이지 UI 구현
- KAN-196
- 우선 local storage 사용하는 코드로 구현했습니다.
- 이후에 mysql 사용하는 코드로 수정하면 됩니다.
[KAN-195]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-195-- feat/배송관리페이지

- package-lock.json
- package.json
- src/App.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/OrderSubscription.jsx
- src/pages/customer/OrderSubscriptionDetail.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-14](https://badgen.net/badge/Preview/PR-14/blue)](https://pr-14.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 주문관리페이지 UI 구현
- KAN-187
- KAN-188
- KAN-189
- KAN-190
- react-moment 삭제했습니다!
- 배송주기, 배송요일 등의 데이터를 어느 경로로 가져와야 할지 모르겠습니다. (우선 이쪽 데이터는 비워뒀습니다.)
[KAN-114]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-114  feat/주문관리페이지 UI 구현

- src/App.jsx
- src/pages/customer/MemberManage.jsx
- src/pages/customer/MemberManageDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-15](https://badgen.net/badge/Preview/PR-15/blue)](https://pr-15.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 관리 페이지 UI 구현
- KAN-175
- KAN-176
- 주소 데이터를 어떻게 가져와야 할까요...
> KAN-110 feat/회원관리페이지 UI 구현

- src/apis/index.js
- src/components/Modals/TimeAttackApplyModal.jsx
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductTimesale.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-18](https://badgen.net/badge/Preview/PR-18/blue)](https://pr-18.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 데이터 불러오기 기능 수정(수정중)
- KAN-180
- 데이터가 불러와지지 않는 문제 발생... 경로가 잘못되었나....... 우선 보류합니다.
> Kan-113  refactor/식품관리 타임 세일 식품 조회 UI 기능 수정 

- src/App.jsx
- src/apis/data.json
- src/apis/index.js
- src/pages/customer/MemberManage.jsx
- src/pages/customer/MemberManageDetail.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/ProductGeneralDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-20](https://badgen.net/badge/Preview/PR-20/blue)](https://pr-20.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 조회 페이지 데이터 요청 방법 수정
- 회원 상세 페이지 데이터 요청 방법 수정
- KAN-176
- KAN-175
- 회원 상세 페이지에서 주소지와 결제수단을 탭을 통해 정보 조회하도록 할 예정
> Kan-175  refactor/회원관리 데이터 요청 방법 수정

- src/App.jsx
- src/apis/apisCommon.js
- src/apis/apisOrders.js
- src/apis/apisProducts.js
- src/apis/index.js
- src/pages/customer/ImageUploadTest.jsx
- src/pages/customer/Inventory.jsx
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductGeneral.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-24](https://badgen.net/badge/Preview/PR-24/blue)](https://pr-24.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 등록 api 연동
KAN-520
KAN-185
KAN-521
- 식품 조회 api 연동 작업 후 페이지끼리 연결 예정 (등록 후 조회 페이지로 넘어가기)
> Kan-113  feat: 식품관리 식품 등록 api 연동

- src/App.jsx
- src/apis/apisCommon.js
- src/apis/apisOrders.js
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/OrderSubscription.jsx
- src/pages/customer/OrderSubscriptionDetail.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-26](https://badgen.net/badge/Preview/PR-26/blue)](https://pr-26.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 일반 주문 조회 api 연동
- 일반 주문 상세 api 연동
KAN-547
KAN-548
KAN-557
- status 별 개수 api 연동해야 함
> Kan-114  feat: 주문관리 일반 주문 조회 및 상세 api 연동

- src/apis/apisMembers.js
- src/pages/customer/MemberManage.jsx
- src/pages/customer/MemberManageDetail.jsx
- src/pages/customer/OrderSubscriptionDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-27](https://badgen.net/badge/Preview/PR-27/blue)](https://pr-27.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 조회 페이지 api 연동
- 회원 상세 페이지 api 연동
KAN-562
KAN-537
> Kan-175  feat: 회원관리 api 연동

- src/App.jsx
- src/apis/apisOrders.js
- src/apis/apisShipments.js
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/Shipment.jsx
- src/pages/customer/ShipmentDetail.jsx
[![KAN-191](https://badgen.net/badge/JIRA/KAN-191/blue?icon=jira)](https://jira.company.com/browse/KAN-191) [![PR-28](https://badgen.net/badge/Preview/PR-28/blue)](https://pr-28.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 출고 조회 페이지 api 연동
- 출고 상세 페이지 api 연동
- KAN-520
- KAN-502
- KAN-607
[KAN-191]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-191  feat: 출고조회 및 출고상세 페이지 api 연동

- src/apis/apisMembers.js
- src/pages/customer/MemberManageDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-29](https://badgen.net/badge/Preview/PR-29/blue)](https://pr-29.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 기본 결제 수단 가장 상위로 올리기
- KAN-442
> Kan-175  refactor: 회원관리 상세조회 결제수단 UI 수정

- src/apis/apisMembers.js
- src/pages/customer/MemberManage.jsx
- src/pages/customer/Shipment.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-30](https://badgen.net/badge/Preview/PR-30/blue)](https://pr-30.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 조회 테이블 필터 기능 수정
- 주석 삭제
- KAN-537
> KAN-175  refactor: 회원관리 필터 기능 수정

- src/pages/customer/Shipment.jsx
[![KAN-191](https://badgen.net/badge/JIRA/KAN-191/blue?icon=jira)](https://jira.company.com/browse/KAN-191) [![PR-31](https://badgen.net/badge/Preview/PR-31/blue)](https://pr-31.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 기간 검색 기능 추가
- KAN-502
> KAN-502 refactor: 출고관리 조회 api 연동 수정

- src/App.jsx
- src/pages/customer/ProductCreate.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-33](https://badgen.net/badge/Preview/PR-33/blue)](https://pr-33.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 구현 기능을 적어주세요.
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
> KAN-184 refactor: 식품 등록 시 조회 페이지로 이동 기능 추가

- src/pages/customer/OrderSubscription.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-34](https://badgen.net/badge/Preview/PR-34/blue)](https://pr-34.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 구현 기능을 적어주세요.
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
> Kan-114  feat: 체크용 pr

- src/App.jsx
- src/apis/apisProducts.js
- src/components/Layouts/Sidenav.jsx
- src/pages/customer/MemberManage.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductEcoDetail.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductGeneralDetail.jsx
- src/pages/customer/ProductTimeSaleDetail.jsx
- src/pages/customer/ProductTimesale.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-35](https://badgen.net/badge/Preview/PR-35/blue)](https://pr-35.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 조회 api 연동
- 식품 상세 조회 api 연동 (연동 중)
- KAN-523
- KAN-524
- KAN-648
- KAN-649
- KAN-525
- KAN-650
- 상세 조회 페이지 UI 구현 필요
- 상세 조회 페이지 수정, 삭제 구현 필요
> Kan 113  feat: 식품관리 조회 api 연동

- src/App.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-36](https://badgen.net/badge/Preview/PR-36/blue)](https://pr-36.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 구현 기능을 적어주세요.
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
> KAN-650 오류 체크용 pr

- src/apis/apisProducts.js
- src/components/Buttons/RegisterButton.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductGeneral.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-38](https://badgen.net/badge/Preview/PR-38/blue)](https://pr-38.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 타임세일 식품 신청 api 연동
- KAN-659
> KAN-659 feat: 타임세일 식품 신청 api 연동

- src/apis/apisInventory.js
- src/pages/customer/Inventory.jsx
[![KAN-117](https://badgen.net/badge/JIRA/KAN-117/blue?icon=jira)](https://jira.company.com/browse/KAN-117) [![PR-39](https://badgen.net/badge/Preview/PR-39/blue)](https://pr-39.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 재고관리 재고조회 api 연동
- KAN-668
[KAN-117]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-117  feat: 재고관리 재고조회 api 연동

- src/apis/apisInventory.js
- src/pages/customer/Inventory.jsx
[![KAN-117](https://badgen.net/badge/JIRA/KAN-117/blue?icon=jira)](https://jira.company.com/browse/KAN-117) [![PR-40](https://badgen.net/badge/Preview/PR-40/blue)](https://pr-40.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 재고 등록 api 연동
- 재고 수량 추가 api 연동
- KAN-669
- 현재 재고 등록 및 추가 db에 업데이트 후 테이블에 바로 반영되지 않음(새로고침 필요) -> 이 부분 수정 예정
- 일반 식품 조회, 친환경 식품 조회 페이지의 table에 재고등록 api 연동하기
[KAN-117]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-117  feat: 재고관리 재고 등록 및 수량 추가 api 연동

- src/apis/apisPromotion.js
- src/pages/customer/Promotion.jsx
[![KAN-115](https://badgen.net/badge/JIRA/KAN-115/blue?icon=jira)](https://jira.company.com/browse/KAN-115) [![PR-41](https://badgen.net/badge/Preview/PR-41/blue)](https://pr-41.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 상단 노출 내역 조회 api 연동
- KAN-674
- 기간 검색 기능.......... 아직 구현 중..........
> Kan-115  feat: 프로모션관리 상단 노출 내역 조회 api 연동

- src/apis/apisProducts.js
- src/components/Buttons/PromotionApplyButton.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductGeneral.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-42](https://badgen.net/badge/Preview/PR-42/blue)](https://pr-42.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 조회 페이지에서 상단 노출 신쳥 api 연동
- KAN-675
> Kan-113  feat: 식품관리 식품 조회 페이지 상단 노출 신청 api 연동

- src/apis/apisDelivery.js
- src/pages/customer/Delivery.jsx
[![KAN-195](https://badgen.net/badge/JIRA/KAN-195/blue?icon=jira)](https://jira.company.com/browse/KAN-195) [![PR-44](https://badgen.net/badge/Preview/PR-44/blue)](https://pr-44.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 배송관리 페이지 배송상태 카운트 api 연동
- KAN-680
[KAN-195]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-195  feat: 배송관리 배송상태 카운트 api 연동

- package-lock.json
- package.json
- src/App.jsx
- src/components/Login/LoginPage.jsx
- src/components/Login/ProtectedRoute.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/Shipment.jsx
- src/stores/useAuthStore.js
[![KAN-683](https://badgen.net/badge/JIRA/KAN-683/blue?icon=jira)](https://jira.company.com/browse/KAN-683) [![PR-45](https://badgen.net/badge/Preview/PR-45/blue)](https://pr-45.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 로그인 토큰 기능 붙이기
- KAN-683
[KAN-683]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-683  feat: 로그인토큰관리

- src/App.css
- src/App.jsx
- src/components/Easyview/LargeCursor.jsx
- src/components/Easyview/layout/EasyViewContent.jsx
- src/components/Easyview/layout/EasyViewHeader.jsx
- src/components/Easyview/layout/EasyViewHeader.module.css
- src/components/Easyview/layout/EasyViewLayout.jsx
- src/components/Easyview/layout/MenuItems.jsx
- src/components/Easyview/layout/VoiceWaveButton.jsx
- src/components/Easyview/member/AddressList.jsx
- src/components/Easyview/member/CardList.jsx
- src/components/Easyview/product/ProductApplyModal.jsx
- src/components/Easyview/product/TimeSaleApplyModal.jsx
- src/components/Layouts/Main.jsx
- src/components/Layouts/MainHeader.jsx
- src/components/Layouts/Sidenav.jsx
- src/index.css
- src/main.jsx
- src/pages/customer/MemberManage.jsx
- src/pages/easyview/EasyMemberManage.jsx
- src/pages/easyview/EasyProductGeneral.jsx
- src/stores/fontSizeStore.js
- src/stores/largeCursorStore.js
- src/stores/speechStore.js
[![KAN-693](https://badgen.net/badge/JIRA/KAN-693/blue?icon=jira)](https://jira.company.com/browse/KAN-693) [![PR-47](https://badgen.net/badge/Preview/PR-47/blue)](https://pr-47.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 음성 기능
- 쉽게 보기 레이아웃 기능
- KAN-693
- 서로 폴더는 다르지만 간섭하는 것이 많아, 충돌 시 무조건 연락 바랍니다.
[KAN-693]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-693 feat: 쉽게 보기 페이지

- src/components/Layouts/Sidenav.module.css
- src/index.css
[![KAN-513](https://badgen.net/badge/JIRA/KAN-513/blue?icon=jira)](https://jira.company.com/browse/KAN-513) [![PR-48](https://badgen.net/badge/Preview/PR-48/blue)](https://pr-48.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- navbar 디자인(색상) 수정
- KAN-691
- KAN-515
[KAN-513]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-513  style: 메인디자인설정 navbar 디자인 수정

- src/apis/apisMembers.js
- src/apis/apisProducts.js
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductEcoDetail.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductGeneralDetail.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-49](https://badgen.net/badge/Preview/PR-49/blue)](https://pr-49.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 상세 조회 api 연동
- KAN-648
- KAN-649
[KAN-113]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-113  feat: 식품관리 상세 조회 api 연동

- src/pages/customer/MemberManage.jsx
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductEcoDetail.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductGeneralDetail.jsx
- src/stores/useAuthStore.js
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-51](https://badgen.net/badge/Preview/PR-51/blue)](https://pr-51.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 등록 페이지 UI 수정
- KAN184
- KAN-683
- KAN-699
- 등록 api 잘 작동하는지 확인 필요
[KAN-113]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-113  style: 식품관리 식품 등록 UI 수정

- src/pages/customer/ShipmentDetail.jsx
[![KAN-191](https://badgen.net/badge/JIRA/KAN-191/blue?icon=jira)](https://jira.company.com/browse/KAN-191) [![PR-52](https://badgen.net/badge/Preview/PR-52/blue)](https://pr-52.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 출고 상세 페이지 UI 수정
- KAN-194
[KAN-191]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-194 style: 출고 상세 페이지 UI 수정

- src/components/Buttons/StatusChangeButton.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/OrderSubscription.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-53](https://badgen.net/badge/Preview/PR-53/blue)](https://pr-53.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 일반 주문 상세 페이지 UI 수정
- KAN-189
- 조회 페이지에서 데이터 props 로 넘겨 받을 때 문제 발생
> Kan-114  style: 주문관리 상세 페이지 UI 수정

- src/pages/customer/MemberManageDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-57](https://badgen.net/badge/Preview/PR-57/blue)](https://pr-57.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 상세 페이지 기본 정보 탭 UI 수정
- KAN-176
> KAN-176 style: 회원 상세 페이지 기본정보 UI 수정

- src/apis/apisProducts.js
- src/apis/apisPromotion.js
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductGeneralDetail.jsx
- src/pages/customer/ProductTimeSaleDetail.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-58](https://badgen.net/badge/Preview/PR-58/blue)](https://pr-58.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 타임세일 식품 취소 api 연동
- 식품 등록 api 연동 수정
- UI 수정
- KAN-520
- KAN-18
- KAN-708
[KAN-113]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kan-113  feat: 식품관리 타임세일식품 취소 api 연동

- src/apis/apisStatistics.js
- src/pages/customer/Statistics.jsx
[![KAN-709](https://badgen.net/badge/JIRA/KAN-709/blue?icon=jira)](https://jira.company.com/browse/KAN-709) [![PR-59](https://badgen.net/badge/Preview/PR-59/blue)](https://pr-59.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 통계페이지 성별선호상품 API 연결
- Close#{709}
> KAN-709 feat: 통계페이지 성별선호상품 API 연결

- src/apis/apisStatistics.js
- src/pages/customer/Statistics.jsx
[![KAN-710](https://badgen.net/badge/JIRA/KAN-710/blue?icon=jira)](https://jira.company.com/browse/KAN-710) [![PR-61](https://badgen.net/badge/Preview/PR-61/blue)](https://pr-61.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 통계페이지 연령별선호상품 API 연결
- Close#{710}
[KAN-710]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-710 feat: 통계페이지 연령별선호상품 API 연결

- package-lock.json
- package.json
- src/components/Login/LoginPage.jsx
- src/components/Login/Onboarding.jsx
- src/components/Login/Slider.jsx
- src/components/Login/slider.module.css
[![KAN-711](https://badgen.net/badge/JIRA/KAN-711/blue?icon=jira)](https://jira.company.com/browse/KAN-711) [![PR-62](https://badgen.net/badge/Preview/PR-62/blue)](https://pr-62.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 온보딩페이지 구현
- Close#{711}
[KAN-711]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-711 feat: 온보딩페이지 구현

- src/apis/apisOrders.js
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/OrderSubscription.jsx
- src/pages/customer/OrderSubscriptionDetail.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-63](https://badgen.net/badge/Preview/PR-63/blue)](https://pr-63.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 일반 주문 조회 api 연동 수정
- 정기 주문 조회 api 연동 수정
- 정기 주문 상세 정보 UI 수정
- KAN-547
- KNA-557
- KAN-190
- KAN-635
> Kan-114  feat: 주문관리 주문조회 api 연동 수정

- package-lock.json
- package.json
- src/apis/apisStatistics.js
- src/components/Chart/BarChart.jsx
- src/components/Chart/PieChart.jsx
- src/pages/customer/Statistics.jsx
[![KAN-715](https://badgen.net/badge/JIRA/KAN-715/blue?icon=jira)](https://jira.company.com/browse/KAN-715) [![PR-65](https://badgen.net/badge/Preview/PR-65/blue)](https://pr-65.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 통계페이지 주문타입별 선호상품 API 연결
- Close#{715}
[KAN-715]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-715 feat: 통계페이지 주문타입별 선호상품 API 연결

- .github/workflows/dashboard-aws.yml
- src/apis/apisCommon.js
- src/pages/customer/Statistics.jsx
- src/stores/useAuthStore.js
[![KAN-722](https://badgen.net/badge/JIRA/KAN-722/blue?icon=jira)](https://jira.company.com/browse/KAN-722) [![PR-66](https://badgen.net/badge/Preview/PR-66/blue)](https://pr-66.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 대시보드 배포자동화스크립트 수정
- Close#{722}
[KAN-722]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-722 refactor: 대시보드 배포자동화스크립트 수정

- src/stores/useAuthStore.js
[![KAN-723](https://badgen.net/badge/JIRA/KAN-723/blue?icon=jira)](https://jira.company.com/browse/KAN-723) [![PR-68](https://badgen.net/badge/Preview/PR-68/blue)](https://pr-68.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 대시보드 access-token관련 버그 수정
- Close#{723}
[KAN-723]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-723 refactor: 대시보드 access-token관련 버그 수정

- src/App.jsx
- src/apis/apisMembers.js
- src/pages/customer/MemberManage.jsx
- src/pages/customer/MemberManageDetail.jsx
[![KAN-175](https://badgen.net/badge/JIRA/KAN-175/blue?icon=jira)](https://jira.company.com/browse/KAN-175) [![PR-70](https://badgen.net/badge/Preview/PR-70/blue)](https://pr-70.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 주소지 조회가 안 되는 경우 '등록된 주소지가 없습니다' 멘트 뜨기.
- KAN-537
> KAN-537 refactor: 회원관리 회원상세 메세지 수정

- src/apis/apisProducts.js
- src/pages/customer/MemberManage.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductEcoDetail.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductGeneralDetail.jsx
- src/pages/customer/ProductTimesale.jsx
[![KAN-113](https://badgen.net/badge/JIRA/KAN-113/blue?icon=jira)](https://jira.company.com/browse/KAN-113) [![PR-71](https://badgen.net/badge/Preview/PR-71/blue)](https://pr-71.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 식품 페이지 오류 사항 수정
- KAN-727
[KAN-113]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-727 refactor: 식품 페이지 오류 수정

- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/OrderGeneralDetail.jsx
- src/pages/customer/OrderSubscription.jsx
- src/pages/customer/OrderSubscriptionDetail.jsx
[![KAN-114](https://badgen.net/badge/JIRA/KAN-114/blue?icon=jira)](https://jira.company.com/browse/KAN-114) [![PR-72](https://badgen.net/badge/Preview/PR-72/blue)](https://pr-72.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 주문 페이지 수정 사항
- KAN-729
[KAN-114]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-729 refactor: 주문 페이지 수정 사항

- src/components/Layouts/MainHeader.jsx
- src/components/Login/LoginPage.jsx
[![KAN-683](https://badgen.net/badge/JIRA/KAN-683/blue?icon=jira)](https://jira.company.com/browse/KAN-683) [![PR-77](https://badgen.net/badge/Preview/PR-77/blue)](https://pr-77.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 로그아웃 기능 추가
- 쉽게보기 버튼 추가
- KAN-691
[KAN-683]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-691 refactor: 로그아웃 기능 추가 및 쉽게보기 버튼 추가

- src/apis/apisStatistics.js
- src/pages/customer/Statistics.jsx
[![KAN-740](https://badgen.net/badge/JIRA/KAN-740/blue?icon=jira)](https://jira.company.com/browse/KAN-740) [![PR-78](https://badgen.net/badge/Preview/PR-78/blue)](https://pr-78.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 통계페이지 필터링 API 연결
- Close#{740}
[KAN-740]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-740 feat: 통계페이지 필터링 API 연결

- package-lock.json
- package.json
- src/App.jsx
- src/components/Easyview/layout/MenuItems.jsx
- src/components/Layouts/Sidenav.jsx
- src/components/Layouts/Sidenav.module.css
- src/pages/customer/Delivery.jsx
- src/pages/customer/Inventory.jsx
- src/pages/customer/MemberAddress.jsx
- src/pages/customer/MemberManage.jsx
- src/pages/customer/MemberManageDetail.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/ProductCreate.jsx
- src/pages/customer/ProductEco.jsx
- src/pages/customer/ProductGeneral.jsx
- src/pages/customer/ProductTimesale.jsx
- src/pages/customer/Promotion.jsx
- src/pages/customer/Shipment.jsx
- src/pages/customer/ShipmentDetail.jsx
[![KAN-743](https://badgen.net/badge/JIRA/KAN-743/blue?icon=jira)](https://jira.company.com/browse/KAN-743) [![PR-80](https://badgen.net/badge/Preview/PR-80/blue)](https://pr-80.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 버그 수정
- KAN-743
- moment-timezone 설치 하였으니 npm ci 하셔야합니다.
[KAN-743]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-743 fix: 버그 수정

- src/pages/easyview/delivery/EasyDelivery.jsx
- src/pages/easyview/inventory/EasyInventory.jsx
- src/pages/easyview/member/EasyMemberManage.jsx
- src/pages/easyview/order/EasyOrderGeneral.jsx
- src/pages/easyview/order/EasyOrderGeneralDetail.jsx
- src/pages/easyview/order/EasyOrderSubscription.jsx
- src/pages/easyview/order/EasyOrderSubscriptionDetail.jsx
- src/pages/easyview/product/EasyProductEco.jsx
- src/pages/easyview/product/EasyProductEcoDetail.jsx
- src/pages/easyview/product/EasyProductGeneral.jsx
- src/pages/easyview/product/EasyProductGeneralDetail.jsx
- src/pages/easyview/product/EasyProductTimeSale.jsx
- src/pages/easyview/product/EasyProductTimeSaleDetail.jsx
- src/pages/easyview/promotion/EasyPromotion.jsx
- src/pages/easyview/shipment/EasyShipment.jsx
- src/pages/easyview/shipment/EasyShipmentDetail.jsx
- src/pages/easyview/statistics/EasyStatistics.jsx
[![KAN-744](https://badgen.net/badge/JIRA/KAN-744/blue?icon=jira)](https://jira.company.com/browse/KAN-744) [![PR-81](https://badgen.net/badge/Preview/PR-81/blue)](https://pr-81.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 페이지 구현
- 버그 수정
- Close#{KAN-741}
- KAN-744
[KAN-744]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-744 fix: 쉽게 보기 버그 수정

- src/apis/apisMain.js
- src/components/Layouts/MainHeader.jsx
- src/pages/Home.jsx
- src/pages/customer/Shipment.jsx
[![KAN-714](https://badgen.net/badge/JIRA/KAN-714/blue?icon=jira)](https://jira.company.com/browse/KAN-714) [![PR-83](https://badgen.net/badge/Preview/PR-83/blue)](https://pr-83.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 메인페이지 기능 완성
- KAN-116
[KAN-714]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-116 feat: 메인 페이지 기능 완성

- src/components/Layouts/MainHeader.jsx
- src/pages/Home.jsx
- src/pages/customer/OrderGeneral.jsx
- src/pages/customer/Shipment.jsx
[![KAN-513](https://badgen.net/badge/JIRA/KAN-513/blue?icon=jira)](https://jira.company.com/browse/KAN-513) [![PR-85](https://badgen.net/badge/Preview/PR-85/blue)](https://pr-85.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 수정 사항 해결
- KAN-691
[KAN-513]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KAN-691 refactor: 수정 사항
